[theme]
base="dark"
primaryColor="#00c15ae6"
backgroundColor="#1f1f1f"
secondaryBackgroundColor="#193d2a"
textColor="#FFFFFF"
font="monospace"
borderColor="#00c15ae6"
baseFontSize=12
headingFontSizes= [
     "2.0rem",
     "1.8rem",
     "1.6rem",
     "1.4rem",
     "1.2rem",
     "1rem"
]

[client]
showSidebarNavigation = false
